### ISSUE TITLE
java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/hhaven

### ISSUE THREAD

**Issue by SuperKaninchen** [JBDCE/uwuScammer#1]
Hi
I compiled the sources using `javac` and tried to execute Main.java using `java Main.java`
But upon execution it just kinda says
`java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/hhaven`
and
`DBConn Failed.. Fix yo network.`

pls help

**Comment by JBDCE** [comment]
You are most likely missing the external library of the jdbc mysql connector found here: https://www.mysql.com/de/products/connector/

But even with that you need a very specific database to run this. 
If you want to use your own database then change the database access information to the one fitted to your database.

Good luck and have fun
